### ISSUE TITLE
Test failures in `ContainerTest` of project `airomem-direct`

### ISSUE THREAD

**Issue by McPringle** [airomem/airomem#9]
```
$ mvn clean package
[…]
Failed tests:   shouldNotStoreHTTPGetMethodChanges(pl.setblack.airomem.direct.ContainerTest): expected:<0> but was:<128>
  shouldNotStoreWriteMethodChanges(pl.setblack.airomem.direct.ContainerTest): expected:<14> but was:<142>
[…]
```

**Comment by jarekratajski** [comment]
I have fixed tests but quite honestly I do not consider  JEE magic solution good anymore. You can experiment and I can help - but I do not think I will extend this part of the project. (I am now doing big simplifications and redesign of airomem-core - I am not sure if I can port it to airomem-direct).
